//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _02.WeekDayService.Console.WeekDayService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeekDayService.IWeekDayService")]
    public interface IWeekDayService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeekDayService/GetWeekDayInBulgarian", ReplyAction="http://tempuri.org/IWeekDayService/GetWeekDayInBulgarianResponse")]
        string GetWeekDayInBulgarian(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeekDayService/GetWeekDayInBulgarian", ReplyAction="http://tempuri.org/IWeekDayService/GetWeekDayInBulgarianResponse")]
        System.Threading.Tasks.Task<string> GetWeekDayInBulgarianAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeekDayServiceChannel : _02.WeekDayService.Console.WeekDayService.IWeekDayService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeekDayServiceClient : System.ServiceModel.ClientBase<_02.WeekDayService.Console.WeekDayService.IWeekDayService>, _02.WeekDayService.Console.WeekDayService.IWeekDayService {
        
        public WeekDayServiceClient() {
        }
        
        public WeekDayServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeekDayServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeekDayServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeekDayServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetWeekDayInBulgarian(System.DateTime date) {
            return base.Channel.GetWeekDayInBulgarian(date);
        }
        
        public System.Threading.Tasks.Task<string> GetWeekDayInBulgarianAsync(System.DateTime date) {
            return base.Channel.GetWeekDayInBulgarianAsync(date);
        }
    }
}
